apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonar-app
  namespace: sonar
spec:
  dnsNames:
  - << Your FQDN >>
  secretName: sonar-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
